# Fig. 3e: Expression fold-change scatterplot highlighting nitrite reductase genes.
#
# Inputs : Fig3abcd_RT_ApoEpi_vs_ApoEpi.csv
#          Fig3abcd_RT_SymGas_vs_SymEpi.csv
#          Fig3abcd_RT_SymGas_vs_ApoGas.csv
#          Fig3abcd_RT_SymEpi_vs_ApoEpi.csv
#          (generated by Fig3abcd_DE_PCA.Rmd)
# Output : Fig3e_NiR.pdf
# Run with this folder as the working directory.

library(tidyverse)

load_contrast <- function(file, suffix) {
  read_csv(file) %>%
    dplyr::select(target_id, qval, b) %>%
    mutate(qsig = if_else(is.na(qval), 0, as.numeric(qval < 0.05)),
           b    = replace_na(b, 0)) %>%
    rename(!!paste0("qval_", suffix) := qval,
           !!paste0("b_",    suffix) := b,
           !!paste0("qsig_", suffix) := qsig)
}

anac <- load_contrast("Fig3abcd_RT_ApoEpi_vs_ApoEpi.csv", "anac")
snsc <- load_contrast("Fig3abcd_RT_SymGas_vs_SymEpi.csv", "snsc")
snan <- load_contrast("Fig3abcd_RT_SymGas_vs_ApoGas.csv", "snan")
scac <- load_contrast("Fig3abcd_RT_SymEpi_vs_ApoEpi.csv", "scac")

expr <- reduce(list(anac, snsc, snan, scac), left_join, by = "target_id") %>%
  select(target_id,
         qsig_anac, qsig_snsc, qsig_snan, qsig_scac,
         b_anac, b_snsc, b_snan, b_scac) %>%
  mutate(across(starts_with("qsig_"), as.factor))

expr_long <- expr %>%
  pivot_longer(cols = c(b_anac, b_snsc, b_snan, b_scac),
               names_to = "Group", values_to = "b_value") %>%
  pivot_longer(cols = c(qsig_anac, qsig_snsc, qsig_snan, qsig_scac),
               names_to = "qsig_group", values_to = "qsig_value") %>%
  filter(Group == sub("qsig_", "b_", qsig_group))

# Nitrite reductase transcripts of interest
nit_id <- c("SymEpi1_26531trans", "SymEpi5_90966trans", "SymGas1_112698trans",
            "SymGas3_92018trans", "SymGas3_97900trans", "SymGas4_73899trans",
            "SymGas4_73900trans", "SymGas2_3111trans", "SymGas2_53733trans",
            "SymGas2_122628trans", "SymGas2_122642trans", "SymGas2_144464trans")

ggplot() +
  geom_point(data = expr_long %>% filter(qsig_value == 0),
             aes(x = Group, y = b_value),
             color = "#d9d9d9", alpha = 0.6, size = 2,
             position = position_jitter(width = 0.4, height = 0)) +
  geom_point(data = expr_long %>% filter(qsig_value == 1),
             aes(x = Group, y = b_value),
             color = "#67a9cf", size = 2, alpha = 0.5,
             position = position_jitter(width = 0.4, height = 0)) +
  geom_point(data = expr_long %>% filter(target_id %in% nit_id),
             aes(x = Group, y = b_value),
             color = "#cb181d", size = 2,
             position = position_jitter(width = 0.4, height = 0)) +
  labs(y = "ln(fold-change)") +
  theme_classic() +
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("Fig3e_NiR.pdf", width = 8, height = 7)
